### ISSUE TITLE
Is the keeping-up-with-updates documentation sufficient?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/Documentation#1]
On this [keeping-up-with-updates documentation page](http://terria.io/Documentation/guide/getting-started/#keeping-up-with-updates) it says:
```
rm -rf node_modules
npm install
```
but in the past as least, I've had to do the more involved:
```
#      check to make sure package.json points to master branch on github, e.g.
#     "terriajs": "git://github.com/TerriaJS/terriajs.git#master",
npm install 
gulp sync-terriajs-dependencies
rm -rf node_modules
npm install 
```

**Comment by kring** [comment]
The extra `sync-terriajs-dependencies` step should only be necessary if you're using a pre-release version of TerriaJS (i.e. a branch of even master prior to it being published to npm).  If you're sticking with npm-published versions of TerriaJS, as described in that Getting Started page, the dependencies should already be in sync.

We do mention `sync-terriajs-dependencies` [here](http://terria.io/Documentation/guide/contributing/development-environment/), but it could probably be more obvious.

**Comment by rsignell-usgs** [comment]
Hmm, not sure then whether to close, so leaving this open...
